name: app
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  sizer: ^2.0.15
  http: ^0.13.4
  flutter_native_splash: ^2.2.4
  shared_preferences: ^2.0.15
  cached_network_image: ^3.2.1
  font_awesome_flutter: ^10.1.0
  flutter_secure_storage: ^5.0.2
  flutter_bloc: ^8.0.1
  equatable: ^2.0.3
  google_fonts: ^3.0.1
  bloc: ^8.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

